# Generated by Django 4.2.20 on 2025-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TransferType",
                    models.CharField(
                        choices=[
                            ("Train", "Train"),
                            ("Bus", "Bus"),
                            ("Domestic Flight", "Domestic Flight"),
                            ("International Flight", "International Flight"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "From",
                    models.CharField(
                        choices=[
                            ("Tehran", "Tehran"),
                            ("Shiraz", "Shiraz"),
                            ("Mashhad", "Mashhad"),
                            ("Gheshm", "Gheshm"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "To",
                    models.CharField(
                        choices=[
                            ("Tehran", "Tehran"),
                            ("Shiraz", "Shiraz"),
                            ("Mashhad", "Mashhad"),
                            ("Gheshm", "Gheshm"),
                            ("London", "London"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "passenger",
                    models.CharField(
                        choices=[
                            ("First Class", "First Class"),
                            ("Economy", "Economy"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "Price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
                ),
                ("Date", models.DateTimeField()),
            ],
        ),
    ]
