from .Tripsview import TripsView
from .BasicView import BasicView
from .HotelView import HotelView
from .RoomView import RoomView
from .UserView import RegisterView,LoginView,ProfileView,LogoutView
from .Tripsview import TripsView
from .TripBookView import TripBookView
from .RoomBookView import RoomBookView
from .ReviewView import Review